/**
 * Les compétences — des exploits, dans le lexique du jeu.
 *
 * **Vocabulaire fermé et obligatoire.** Chacune porte un `role`, un `axe`, une
 * `forme` et un `type`, tirés de listes closes. Et dans une même classe, deux
 * compétences ne peuvent pas partager le couple `(role, forme)` : c'est la
 * règle qui plafonne mécaniquement une classe autour de quatorze compétences
 * réellement différentes, et qui empêche d'en écrire une quinzième qui serait
 * un clone de la sixième. Un test la vérifie.
 *
 * `temps` est le coût de tempo, pas une durée : 0.7 rapide, 1.0 normale,
 * 1.6 lourde, 2.2 ultime.
 */

export const ROLES = ['ouvrir', 'percer', 'tenir', 'soigner', 'deregler', 'finir', 'financer']
export const AXES = ['degat', 'defense', 'tempo', 'economie', 'controle']
export const FORMES = ['cible', 'rang', 'tous', 'soi', 'allie', 'equipe']
export const TYPES = ['brut', 'logique', 'corruption', 'aucun']
export const TAGS = [
  'BRUT',
  'LOGIQUE',
  'CORRUPTION',
  'SOIN',
  'DEPLACE',
  'MARQUE',
  'ZONE',
  'FIN',
  'PARE',
  'CYCLE',
  'CONTACT',
  'PERCE',
]

export const COMPETENCES = [
  // --- ANALYSTE : la révélation. Il transforme l'information en dégâts alliés.
  {
    id: 'sonde',
    nom: 'SONDE',
    classe: 'analyste',
    role: 'ouvrir',
    axe: 'controle',
    forme: 'cible',
    type: 'logique',
    cout: 1,
    temps: 0.7,
    recharge: 0,
    base: 6,
    perce: true,
    etats: [{ q: 'marque', n: 1 }],
    tags: ['LOGIQUE', 'MARQUE', 'PERCE'],
    dit: 'Marque une cible, où qu’elle soit. Peu de dégâts, beaucoup de conséquences.',
  },
  {
    id: 'balayage',
    nom: 'BALAYAGE',
    classe: 'analyste',
    role: 'ouvrir',
    axe: 'controle',
    forme: 'tous',
    type: 'logique',
    cout: 3,
    temps: 1.6,
    recharge: 2,
    base: 5,
    perce: true,
    etats: [{ q: 'marque', n: 1 }],
    tags: ['LOGIQUE', 'MARQUE', 'ZONE', 'PERCE'],
    dit: 'Marque tout le camp adverse d’un coup.',
  },
  {
    id: 'exploit',
    nom: 'EXPLOIT',
    classe: 'analyste',
    role: 'finir',
    axe: 'degat',
    forme: 'cible',
    type: 'logique',
    cout: 3,
    temps: 1.0,
    recharge: 1,
    base: 16,
    perce: true,
    consomme: 'marque',
    tags: ['LOGIQUE', 'FIN', 'PERCE'],
    dit: 'Consomme les marques de la cible et frappe une fois par pile.',
  },
  {
    id: 'rapport',
    nom: 'RAPPORT',
    classe: 'analyste',
    role: 'financer',
    axe: 'economie',
    forme: 'equipe',
    type: 'aucun',
    cout: 0,
    temps: 0.7,
    recharge: 3,
    base: 0,
    cycles: 2,
    tags: ['CYCLE'],
    dit: 'Rend deux cycles à l’équipe. Gratuit, mais lent à revenir.',
  },
  {
    id: 'faille',
    nom: 'FAILLE',
    classe: 'analyste',
    role: 'percer',
    axe: 'degat',
    forme: 'cible',
    type: 'logique',
    cout: 2,
    temps: 1.0,
    recharge: 0,
    base: 12,
    perce: true,
    etats: [{ q: 'fragment', n: 2 }],
    tags: ['LOGIQUE', 'PERCE'],
    dit: 'Ouvre le blindage : deux points de moins, deux tours durant.',
  },
  {
    id: 'brouillage',
    nom: 'BROUILLAGE',
    classe: 'analyste',
    role: 'deregler',
    axe: 'controle',
    forme: 'cible',
    type: 'aucun',
    cout: 2,
    temps: 1.0,
    recharge: 2,
    base: 0,
    perce: true,
    etats: [{ q: 'silence', n: 2 }],
    tags: ['LOGIQUE'],
    dit: 'Le processus ne peut plus lancer que sa frappe de base.',
  },

  // --- BRISEUR : le contact, le blindage, le rang avant.
  {
    id: 'masse',
    nom: 'MASSE',
    classe: 'briseur',
    role: 'percer',
    axe: 'degat',
    forme: 'cible',
    type: 'brut',
    cout: 1,
    temps: 1.0,
    recharge: 0,
    base: 14,
    contact: true,
    tags: ['BRUT', 'CONTACT'],
    dit: 'Un coup franc sur le rang avant. Rien de subtil.',
  },
  {
    id: 'ebranle',
    nom: 'ÉBRANLE',
    classe: 'briseur',
    role: 'ouvrir',
    axe: 'controle',
    forme: 'cible',
    type: 'brut',
    cout: 2,
    temps: 1.0,
    recharge: 1,
    base: 9,
    contact: true,
    etats: [{ q: 'fragment', n: 3 }],
    tags: ['BRUT', 'CONTACT'],
    dit: 'Fend l’armure avant de frapper pour de bon.',
  },
  {
    id: 'onde',
    nom: 'ONDE',
    classe: 'briseur',
    role: 'finir',
    axe: 'degat',
    forme: 'rang',
    type: 'brut',
    cout: 3,
    temps: 1.6,
    recharge: 2,
    base: 13,
    contact: true,
    tags: ['BRUT', 'ZONE', 'FIN', 'CONTACT'],
    dit: 'Balaye tout un rang adverse.',
  },
  {
    id: 'ancre',
    nom: 'ANCRE',
    classe: 'briseur',
    role: 'tenir',
    axe: 'defense',
    forme: 'soi',
    type: 'aucun',
    cout: 1,
    temps: 0.7,
    recharge: 1,
    base: 0,
    etats: [{ q: 'pare', n: 14, sur: 'soi' }],
    tags: ['PARE'],
    dit: 'Se couvre. Le briseur tient le rang avant, encore faut-il qu’il tienne.',
  },
  {
    id: 'charge',
    nom: 'CHARGE',
    classe: 'briseur',
    role: 'deregler',
    axe: 'tempo',
    forme: 'cible',
    type: 'brut',
    cout: 2,
    temps: 1.0,
    recharge: 1,
    base: 10,
    contact: true,
    avance: true,
    etats: [{ q: 'latence', n: 2 }],
    tags: ['BRUT', 'DEPLACE', 'CONTACT'],
    dit: 'Passe au rang avant en frappant, et ralentit ce qu’il percute.',
  },
  {
    id: 'demolition',
    nom: 'DÉMOLITION',
    classe: 'briseur',
    role: 'financer',
    axe: 'degat',
    forme: 'tous',
    type: 'brut',
    cout: 5,
    temps: 2.2,
    recharge: 4,
    base: 18,
    tags: ['BRUT', 'ZONE', 'FIN'],
    dit: 'Tout, partout, une fois par combat ou presque.',
  },

  // --- TISSEUR : la tenue. Pare-feux, correctifs, déplacements.
  {
    id: 'correctif',
    nom: 'CORRECTIF',
    classe: 'tisseur',
    role: 'soigner',
    axe: 'defense',
    forme: 'allie',
    type: 'aucun',
    cout: 2,
    temps: 1.0,
    recharge: 0,
    base: 0,
    soin: 16,
    tags: ['SOIN'],
    dit: 'Répare un opérateur. Le seul soin fiable de l’équipe.',
  },
  {
    id: 'muraille',
    nom: 'MURAILLE',
    classe: 'tisseur',
    role: 'tenir',
    axe: 'defense',
    forme: 'equipe',
    type: 'aucun',
    cout: 3,
    temps: 1.6,
    recharge: 2,
    base: 0,
    etats: [{ q: 'pare', n: 12, sur: 'equipe' }],
    tags: ['PARE', 'ZONE'],
    dit: 'Un pare-feu sur les trois opérateurs.',
  },
  {
    id: 'permutation',
    nom: 'PERMUTATION',
    classe: 'tisseur',
    role: 'deregler',
    axe: 'tempo',
    forme: 'allie',
    type: 'aucun',
    cout: 1,
    temps: 0.7,
    recharge: 0,
    base: 0,
    bascule: true,
    etats: [{ q: 'cache', n: 1, sur: 'cible' }],
    tags: ['DEPLACE'],
    dit: 'Change un allié de rang et le met à couvert un tour.',
  },
  {
    id: 'filtre',
    nom: 'FILTRE',
    classe: 'tisseur',
    role: 'ouvrir',
    axe: 'controle',
    forme: 'rang',
    type: 'aucun',
    cout: 2,
    temps: 1.0,
    recharge: 1,
    base: 0,
    perce: true,
    etats: [{ q: 'latence', n: 2 }],
    tags: ['ZONE'],
    dit: 'Ralentit tout un rang adverse.',
  },
  {
    id: 'suture',
    nom: 'SUTURE',
    classe: 'tisseur',
    role: 'financer',
    axe: 'defense',
    forme: 'allie',
    type: 'aucun',
    cout: 1,
    temps: 0.7,
    recharge: 2,
    base: 0,
    etats: [{ q: 'regenere', n: 3, sur: 'cible' }],
    tags: ['SOIN'],
    dit: 'Trois tours de réparation lente. Moins cher qu’un correctif.',
  },
  {
    id: 'purge',
    nom: 'PURGE',
    classe: 'tisseur',
    role: 'percer',
    axe: 'degat',
    forme: 'cible',
    type: 'logique',
    cout: 2,
    temps: 1.0,
    recharge: 1,
    base: 11,
    perce: true,
    tags: ['LOGIQUE', 'PERCE'],
    dit: 'De quoi se défendre quand personne n’a besoin d’être réparé.',
  },

  // --- VECTEUR : la corruption. Elle ne frappe pas, elle ronge et se propage.
  {
    id: 'injecte',
    nom: 'INJECTE',
    classe: 'vecteur',
    role: 'percer',
    axe: 'degat',
    forme: 'cible',
    type: 'corruption',
    cout: 1,
    temps: 0.7,
    recharge: 0,
    base: 0,
    perce: true,
    fuite: 5,
    tags: ['CORRUPTION', 'PERCE'],
    dit: 'Cinq piles de fuite. Rien ne les arrête — ni blindage, ni pare-feu.',
  },
  {
    id: 'diffuse',
    nom: 'DIFFUSE',
    classe: 'vecteur',
    role: 'ouvrir',
    axe: 'controle',
    forme: 'rang',
    type: 'corruption',
    cout: 2,
    temps: 1.0,
    recharge: 1,
    base: 0,
    perce: true,
    fuite: 3,
    tags: ['CORRUPTION', 'ZONE', 'PERCE'],
    dit: 'Contamine tout un rang à la fois.',
  },
  {
    id: 'ver',
    nom: 'VER',
    classe: 'vecteur',
    role: 'deregler',
    axe: 'degat',
    forme: 'cible',
    type: 'corruption',
    cout: 3,
    temps: 1.0,
    recharge: 2,
    base: 0,
    perce: true,
    fuite: 9,
    etats: [{ q: 'silence', n: 1 }],
    tags: ['CORRUPTION', 'PERCE'],
    dit: 'Neuf piles, et le processus n’a plus que sa frappe de base.',
  },
  {
    id: 'catalyse',
    nom: 'CATALYSE',
    classe: 'vecteur',
    role: 'finir',
    axe: 'degat',
    forme: 'cible',
    type: 'logique',
    cout: 3,
    temps: 1.0,
    recharge: 2,
    base: 9,
    perce: true,
    consomme: 'fuite',
    tags: ['LOGIQUE', 'FIN', 'PERCE'],
    dit: 'Brûle toute la fuite accumulée d’un coup, une frappe par pile.',
  },
  {
    id: 'siphon',
    nom: 'SIPHON',
    classe: 'vecteur',
    role: 'soigner',
    axe: 'defense',
    forme: 'soi',
    type: 'aucun',
    cout: 2,
    temps: 1.0,
    recharge: 2,
    base: 0,
    soin: 12,
    etats: [{ q: 'regenere', n: 2, sur: 'soi' }],
    tags: ['SOIN'],
    dit: 'Il reprend au système ce qu’il lui a donné.',
  },
  {
    id: 'essaimage',
    nom: 'ESSAIMAGE',
    classe: 'vecteur',
    role: 'financer',
    axe: 'controle',
    forme: 'tous',
    type: 'corruption',
    cout: 4,
    temps: 1.6,
    recharge: 3,
    base: 0,
    fuite: 4,
    tags: ['CORRUPTION', 'ZONE'],
    dit: 'Tout le camp adverse commence à fuir.',
  },

  // --- HORLOGE : le tempo. Elle ne frappe pas fort, elle décide de l'ordre.
  {
    id: 'retard',
    nom: 'RETARD',
    classe: 'horloge',
    role: 'ouvrir',
    axe: 'tempo',
    forme: 'cible',
    type: 'logique',
    cout: 1,
    temps: 0.7,
    recharge: 0,
    base: 7,
    perce: true,
    etats: [{ q: 'latence', n: 2 }],
    tags: ['LOGIQUE', 'PERCE'],
    dit: 'Repousse une cible dans la file. Deux tours de retard changent tout.',
  },
  {
    id: 'devance',
    nom: 'DEVANCE',
    classe: 'horloge',
    role: 'financer',
    axe: 'tempo',
    forme: 'soi',
    type: 'aucun',
    cout: 1,
    temps: 0.7,
    recharge: 2,
    base: 0,
    etats: [{ q: 'priorite', n: 1, sur: 'soi' }],
    tags: ['CYCLE'],
    dit: 'La prochaine action ne coûte pas de tempo. Deux coups d’affilée.',
  },
  {
    id: 'accelere',
    nom: 'ACCÉLÈRE',
    classe: 'horloge',
    role: 'tenir',
    axe: 'tempo',
    forme: 'allie',
    type: 'aucun',
    cout: 2,
    temps: 1.0,
    recharge: 1,
    base: 0,
    etats: [{ q: 'surcadence', n: 2, sur: 'cible' }],
    tags: ['CYCLE'],
    dit: 'Un allié joue plus souvent et frappe 20 % plus fort.',
  },
  {
    id: 'gel',
    nom: 'GEL',
    classe: 'horloge',
    role: 'deregler',
    axe: 'controle',
    forme: 'rang',
    type: 'logique',
    cout: 3,
    temps: 1.6,
    recharge: 2,
    base: 6,
    perce: true,
    etats: [{ q: 'latence', n: 3 }],
    tags: ['LOGIQUE', 'ZONE', 'PERCE'],
    dit: 'Tout un rang décroche de la file.',
  },
  {
    id: 'impulsion',
    nom: 'IMPULSION',
    classe: 'horloge',
    role: 'percer',
    axe: 'degat',
    forme: 'cible',
    type: 'logique',
    cout: 2,
    temps: 1.0,
    recharge: 0,
    base: 13,
    perce: true,
    tags: ['LOGIQUE', 'PERCE'],
    dit: 'De quoi frapper quand l’ordre est déjà réglé.',
  },
  {
    id: 'cascade',
    nom: 'CASCADE',
    classe: 'horloge',
    role: 'finir',
    axe: 'tempo',
    forme: 'tous',
    type: 'logique',
    cout: 4,
    temps: 1.6,
    recharge: 3,
    base: 10,
    perce: true,
    etats: [{ q: 'latence', n: 2 }],
    tags: ['LOGIQUE', 'ZONE', 'FIN', 'PERCE'],
    dit: 'Frappe tout le monde et repousse tout le monde.',
  },
]

export const COMP = Object.fromEntries(COMPETENCES.map((c) => [c.id, c]))

/**
 * Les frappes des processus. Elles vivent dans la même table pour que la
 * résolution soit strictement la même des deux côtés — un combat où l'ennemi
 * suit d'autres règles que le joueur est un combat qu'on ne peut pas apprendre.
 */
export const COMPETENCES_PROCESSUS = [
  {
    id: 'p_frappe',
    nom: 'FRAPPE',
    role: 'percer',
    axe: 'degat',
    forme: 'cible',
    type: 'brut',
    cout: 0,
    temps: 1.0,
    recharge: 0,
    base: 15,
    contact: true,
    tags: ['BRUT', 'CONTACT'],
  },
  {
    id: 'p_griffe',
    nom: 'GRIFFE',
    role: 'percer',
    axe: 'degat',
    forme: 'cible',
    type: 'brut',
    cout: 0,
    temps: 0.7,
    recharge: 0,
    base: 10,
    contact: true,
    tags: ['BRUT', 'CONTACT'],
  },
  {
    id: 'p_injection',
    nom: 'INJECTION',
    role: 'deregler',
    axe: 'controle',
    forme: 'cible',
    type: 'corruption',
    cout: 0,
    temps: 1.0,
    recharge: 1,
    base: 0,
    perce: true,
    fuite: 7,
    tags: ['CORRUPTION'],
  },
  {
    id: 'p_salve',
    nom: 'SALVE',
    role: 'finir',
    axe: 'degat',
    forme: 'tous',
    type: 'brut',
    cout: 0,
    temps: 1.6,
    recharge: 2,
    base: 11,
    tags: ['BRUT', 'ZONE'],
  },
  {
    id: 'p_verrou',
    nom: 'VERROU',
    role: 'ouvrir',
    axe: 'controle',
    forme: 'cible',
    type: 'logique',
    cout: 0,
    temps: 1.0,
    recharge: 2,
    base: 8,
    perce: true,
    tags: ['LOGIQUE'],
  },
  {
    id: 'p_blindage',
    nom: 'BLINDAGE',
    role: 'tenir',
    axe: 'defense',
    forme: 'soi',
    type: 'aucun',
    cout: 0,
    temps: 1.0,
    recharge: 2,
    base: 0,
    blinde: 8,
    tags: ['PARE'],
  },
  {
    id: 'p_correctif',
    nom: 'RESTAURE',
    role: 'soigner',
    axe: 'defense',
    forme: 'allie',
    type: 'aucun',
    cout: 0,
    temps: 1.0,
    recharge: 2,
    base: 0,
    soin: 14,
    tags: ['SOIN'],
  },
  {
    id: 'p_ecrase',
    nom: 'ÉCRASE',
    role: 'finir',
    axe: 'degat',
    forme: 'cible',
    type: 'brut',
    cout: 0,
    temps: 1.6,
    recharge: 2,
    base: 28,
    contact: true,
    tags: ['BRUT', 'CONTACT', 'FIN'],
  },
  {
    id: 'p_corrode',
    nom: 'CORRODE',
    role: 'percer',
    axe: 'degat',
    forme: 'rang',
    type: 'corruption',
    cout: 0,
    temps: 1.6,
    recharge: 2,
    base: 0,
    fuite: 5,
    tags: ['CORRUPTION', 'ZONE'],
  },
]

for (const c of COMPETENCES_PROCESSUS) COMP[c.id] = c
