/**
 * Les uniques — la page « ÉTAT-MAJOR » de la caserne.
 *
 * Un générique est une ligne de la table des classes ; un unique est
 * **quelqu'un** : un nom, un titre, une phrase, un grade qu'aucun générique
 * n'atteint, une aptitude signée. On n'en recrute qu'un exemplaire, et une
 * fois perdu il ne revient pas.
 *
 * `rarete` gouverne deux choses à la fois, exactement comme demandé : le prix
 * de recrutement et le taux d'apparition, tous deux indexés sur le niveau de
 * la compagnie (`unites.js`). `rang` est le niveau à partir duquel l'unique
 * peut apparaître — on ne croise pas un commandant à la première escarmouche.
 */

export const RARETES = [
  { id: 1, nom: 'VÉTÉRAN', court: 'V', prix: 1.6, poids: 10 },
  { id: 2, nom: 'GRADÉ', court: 'G', prix: 2.4, poids: 5 },
  { id: 3, nom: 'HÉROS', court: 'H', prix: 3.6, poids: 2 },
  { id: 4, nom: 'LÉGENDE', court: 'L', prix: 5.5, poids: 0.6 },
]

export const RAR = Object.fromEntries(RARETES.map((r) => [r.id, r]))

const u = (id, nom, titre, cl, grade, rarete, rang, bonus, apt, phrase) => ({
  id,
  nom,
  titre,
  cl,
  grade,
  rarete,
  rang,
  bonus,
  apt,
  phrase,
})

export const UNIQUES = [
  // --- Vétérans : on les croise tôt, ils tiennent longtemps -----------------
  u(
    'vasseur',
    'VASSEUR',
    'LE PREMIER ARRIVÉ',
    'milicien',
    1,
    1,
    1,
    { pv: 6, def: 2 },
    ['tenace'],
    'Il était là avant la compagnie. Il y sera après.',
  ),
  u(
    'gerbaud',
    'GERBAUD',
    'DOS AU MUR',
    'piquier',
    1,
    1,
    1,
    { pv: 8, def: 3 },
    ['riposte_ferme'],
    'On ne le contourne pas : on attend qu’il bouge.',
  ),
  u(
    'lhomme',
    'L’HOMME',
    'SANS NOM CONNU',
    'eclaireur',
    1,
    1,
    1,
    { mvt: 1, vue: 2 },
    ['embuscade'],
    'Personne ne sait d’où il vient. Il revient toujours.',
  ),
  u(
    'rouvre',
    'ROUVRE',
    'L’ŒIL DE LA VALLÉE',
    'archer',
    1,
    1,
    2,
    { att: 3 },
    ['precision'],
    'Il compte les pas de l’ennemi avant de compter ses flèches.',
  ),
  u(
    'malorne',
    'MALORNE',
    'LA VIEILLE GARDE',
    'fantassin',
    2,
    1,
    3,
    { pv: 10, def: 3 },
    ['discipline'],
    'Trois guerres. Le même pas.',
  ),
  u(
    'bertaud',
    'BERTAUD',
    'LE CHARRETIER',
    'infirmier',
    1,
    1,
    2,
    { pv: 6 },
    ['soigneur_chef'],
    'Il ramène toujours plus d’hommes qu’il n’en emmène.',
  ),
  u(
    'sirven',
    'SIRVEN',
    'PIED SÛR',
    'frondeur',
    1,
    1,
    2,
    { mvt: 1, att: 2 },
    ['montagnard'],
    'La pente ne l’a jamais ralenti.',
  ),
  u(
    'cazals',
    'CAZALS',
    'LE COMPTEUR',
    'arbaletrier',
    1,
    1,
    3,
    { att: 3 },
    ['sniper'],
    'Un carreau, un homme. Il n’a jamais compris qu’on en gâche.',
  ),
  u(
    'nogaret',
    'NOGARET',
    'LA MULE',
    'sapeur',
    1,
    1,
    4,
    { pv: 8 },
    ['pontonnier'],
    'Il porte le pont sur son dos depuis quatre campagnes.',
  ),
  u(
    'estève',
    'ESTÈVE',
    'DEUX FOIS BLESSÉ',
    'traqueur',
    1,
    1,
    4,
    { att: 3, def: 2 },
    ['vengeance'],
    'Il se souvient de chaque main qui l’a touché.',
  ),

  // --- Gradés : le cœur d'une compagnie -------------------------------------
  u(
    'daurel',
    'DAUREL',
    'SERGENT DE FER',
    'legionnaire',
    2,
    2,
    4,
    { pv: 10, def: 4 },
    ['commandement', 'bouclier'],
    'Sa ligne n’a jamais reculé, même quand il fallait.',
  ),
  u(
    'valcros',
    'VALCROS',
    'LA MAIN GAUCHE',
    'voltigeur',
    2,
    2,
    5,
    { att: 4, mvt: 1 },
    ['tirailleur', 'insaisissable'],
    'On lui a donné un flanc à tenir. Il a pris les deux.',
  ),
  u(
    'mireur',
    'MIREUR',
    'LE PATIENT',
    'tirailleur',
    2,
    2,
    6,
    { att: 4 },
    ['sniper', 'tir_precis'],
    'Il attend. C’est tout ce qu’il fait. C’est assez.',
  ),
  u(
    'brassac',
    'BRASSAC',
    'L’ÉCUYER DEVENU MAÎTRE',
    'cavalier',
    2,
    2,
    5,
    { att: 4, mvt: 1 },
    ['charge_lourde'],
    'Il monte comme on tombe : sans se retenir.',
  ),
  u(
    'fauriel',
    'FAURIEL',
    'TÊTE DE COLONNE',
    'porte_ordre',
    2,
    2,
    6,
    { pv: 6, mvt: 1 },
    ['commandement_large', 'ordre_marche'],
    'Personne ne l’a jamais vu courir. Tout le monde le suit.',
  ),
  u(
    'lomagne',
    'LOMAGNE',
    'LE GÉOMÈTRE',
    'baliste',
    2,
    2,
    7,
    { att: 5 },
    ['perce_armure'],
    'Il dessine la bataille avant de la tirer.',
  ),
  u(
    'carsac',
    'CARSAC',
    'LE MUR',
    'garde',
    2,
    2,
    9,
    { pv: 14, def: 5 },
    ['cuirasse', 'tenace'],
    'On l’a mis là il y a deux heures. Il y est encore.',
  ),
  u(
    'serignan',
    'SÉRIGNAN',
    'LE SOUFFLE COURT',
    'vivandier',
    2,
    2,
    9,
    { pv: 8 },
    ['soigneur_chef', 'ralliement'],
    'Elle arrive toujours avant la peur.',
  ),
  u(
    'bazordan',
    'BAZORDAN',
    'LA HERSE',
    'hallebardier',
    2,
    2,
    6,
    { att: 4, def: 3 },
    ['traque_monte', 'zone_controle'],
    'Il n’attaque pas la cavalerie. Il l’attend.',
  ),
  u(
    'ostabat',
    'OSTABAT',
    'CELUI QUI SAIT OÙ',
    'rodeur',
    2,
    2,
    8,
    { mvt: 1, vue: 2 },
    ['embuscade_maitre'],
    'Il connaît des chemins que la carte ignore.',
  ),
  u(
    'mauvezin',
    'MAUVEZIN',
    'LE MARTEAU',
    'grenadier',
    2,
    2,
    12,
    { att: 5 },
    ['grenade', 'brise_ligne'],
    'Il ne perce pas les lignes : il les décourage.',
  ),
  u(
    'pardaillan',
    'PARDAILLAN',
    'LE VOLTIGEUR GRIS',
    'hussard',
    2,
    2,
    8,
    { mvt: 1, att: 4 },
    ['charge', 'insaisissable'],
    'Le seul qui rentre toujours par où il est sorti.',
  ),

  // --- Héros : ils changent une bataille -------------------------------------
  u(
    'aliénor',
    'ALIÉNOR',
    'LIEUTENANT DE LA MARCHE',
    'lancier',
    3,
    3,
    7,
    { pv: 10, att: 6, mvt: 1 },
    ['charge_lourde', 'commandement'],
    'Elle a pris le commandement à quinze ans, en criant plus fort.',
  ),
  u(
    'roquefeuil',
    'ROQUEFEUIL',
    'LE SILENCE',
    'ombre',
    3,
    3,
    13,
    { att: 6, mvt: 1 },
    ['embuscade_maitre', 'brise_ligne'],
    'On ne le voit qu’une fois.',
  ),
  u(
    'bethmale',
    'BETHMALE',
    'LE PORTEUR DE FEU',
    'mortier',
    3,
    3,
    11,
    { att: 7 },
    ['barrage', 'perce_total'],
    'Il n’a jamais vu ses cibles. Elles l’ont vu.',
  ),
  u(
    'marcillac',
    'MARCILLAC',
    'LIEUTENANT AUX MILLE PAS',
    'dragon',
    3,
    3,
    9,
    { pv: 8, att: 5, mvt: 1 },
    ['tirailleur', 'precision'],
    'Il tire, avance, tire encore. On ne l’atteint jamais.',
  ),
  u(
    'gavarnie',
    'GAVARNIE',
    'LA DERNIÈRE LIGNE',
    'garde',
    3,
    3,
    12,
    { pv: 18, def: 7 },
    ['cuirasse', 'zone_controle', 'tenace'],
    'Derrière lui, il n’y a plus rien à défendre. C’est pour ça.',
  ),
  u(
    'tourmalet',
    'TOURMALET',
    'LE MONTAGNARD',
    'rodeur',
    3,
    3,
    10,
    { att: 6, mvt: 2, vue: 2 },
    ['montagnard', 'embuscade_maitre'],
    'La montagne lui appartient. Il la prête.',
  ),
  u(
    'villandric',
    'VILLANDRIC',
    'LE CHIRURGIEN DE CAMPAGNE',
    'vivandier',
    3,
    3,
    11,
    { pv: 10 },
    ['soigneur_chef', 'soin', 'discipline'],
    'Il a recousu plus d’hommes que la compagnie n’en compte.',
  ),
  u(
    'estaing',
    'ESTAING',
    'LIEUTENANT DE FER',
    'cuirassier',
    3,
    3,
    13,
    { pv: 14, att: 6, def: 4 },
    ['charge_lourde', 'cuirasse'],
    'Le choc l’amuse encore.',
  ),
  u(
    'lauzerte',
    'LAUZERTE',
    'L’ŒIL LONG',
    'marqueur',
    3,
    3,
    12,
    { att: 7, vue: 2 },
    ['sniper', 'tir_precis', 'precision'],
    'Elle a touché à sept cents pas. Deux fois.',
  ),
  u(
    'camarade',
    'MONTGAILLARD',
    'CELUI QU’ON SUIT',
    'tambour',
    3,
    3,
    13,
    { pv: 10 },
    ['commandement_large', 'inspire', 'ralliement'],
    'Le tambour ne s’arrête pas. Personne ne recule.',
  ),

  // --- Légendes : une par compagnie, et on s'en souvient ---------------------
  u(
    'ardenne',
    'ARDENNE',
    'CAPITAINE DE LA VIEILLE COMPAGNIE',
    'brise_ligne',
    4,
    4,
    15,
    { pv: 22, att: 9, def: 6 },
    ['charge_lourde', 'brise_ligne', 'assaut_general'],
    'Trente ans qu’on l’envoie là où ça casse. Ça n’a jamais cassé.',
  ),
  u(
    'valsserre',
    'VALSSERRE',
    'CAPITAINE DES CHEMINS',
    'chevalier',
    4,
    4,
    16,
    { pv: 20, att: 9, def: 7, mvt: 1 },
    ['charge_lourde', 'zone_controle', 'ordre_marche'],
    'On lui a donné une route. Elle a pris la province.',
  ),
  u(
    'noirlac',
    'NOIRLAC',
    'CAPITAINE DE L’ARRIÈRE',
    'canon',
    4,
    4,
    17,
    { pv: 14, att: 11 },
    ['perce_total', 'volee_lourde', 'barrage'],
    'Il n’a jamais donné l’assaut. Il n’en a jamais eu besoin.',
  ),
  u(
    'orbieu',
    'ORBIEU',
    'COMMANDANT DU FRONT',
    'legionnaire',
    5,
    4,
    20,
    { pv: 26, att: 10, def: 9 },
    ['commandement_large', 'tenir_ligne', 'discipline', 'tenace'],
    'La ligne ne rompt pas. C’est un fait, pas un ordre.',
  ),
  u(
    'sauveterre',
    'SAUVETERRE',
    'COMMANDANT SANS BATAILLE PERDUE',
    'hussard',
    5,
    4,
    22,
    { pv: 18, att: 11, def: 5, mvt: 2, vue: 2 },
    ['charge', 'insaisissable', 'assaut_general', 'second_souffle'],
    'Quatorze campagnes. Aucune défaite. Aucune explication.',
  ),
  u(
    'mirepoix',
    'MIREPOIX',
    'LA VOIX DE L’ÉTAT-MAJOR',
    'tambour',
    5,
    4,
    19,
    { pv: 16, def: 6 },
    ['commandement_large', 'inspire', 'ordre_marche', 'ralliement'],
    'Elle ne se bat pas. Elle décide qui se bat, et où.',
  ),
  u(
    'peyrelade',
    'PEYRELADE',
    'L’ARTILLEUR DU ROI',
    'catapulte',
    4,
    4,
    18,
    { pv: 14, att: 10 },
    ['volee_lourde', 'perce_armure', 'barrage'],
    'Il pose ses pièces la veille. Le lendemain, il n’y a plus de colline.',
  ),
  u(
    'aubrac',
    'AUBRAC',
    'LE DERNIER DES ÉCLAIREURS',
    'ombre',
    4,
    4,
    16,
    { att: 8, mvt: 2, vue: 3 },
    ['embuscade_maitre', 'insaisissable', 'brise_ligne', 'fumigene'],
    'Il est passé au travers de trois armées. Personne n’a rien vu.',
  ),
]

export const UQ = Object.fromEntries(UNIQUES.map((x) => [x.id, x]))
